### ISSUE TITLE
Chatops deployment spec

### ISSUE THREAD

**Issue by erichartline** [dictybase-docker/developer-docs#161]
Drafts and ideas go here.

#157

**Comment by erichartline** [comment]
Data we need:

- branch OR commit ID (ref)
- cluster
- namespace (optional?)

`/deploy ref=develop cluster=erickube`
`/deploy ref=62f5f93e327949135ae1a79c201ad703830c7f55 cluster=erickube`

**Comment by erichartline** [comment]
or we could do `/deploy develop erickube`

**Comment by cybersiddhu** [comment]
` /deploy [-r|--ref] <gitref/branch> [-c|--cluster] <cluster-name>`

**Comment by erichartline** [comment]
**Pull requests**

- commit (optional -- if not included, use head commit)
- cluster

`/deploy-pr commit=xyz cluster=erickube`
`/deploy-pr cluster=erickube`
`/deploy-pr cluster=siddkube commit=foo`

**Comment by wildlifehexagon** [comment]
Deploy anywhere

- ref (branch or ID)
- cluster

`/deploy branch=develop cluster=erickube`
`/deploy id=xyz cluster=erickube`
`/deploy cluster=siddkube id=foo`

**Comment by cybersiddhu** [comment]
# Subcommand based design
`/deploy [--global-options] [subcommand] [what-do-deploy]`
`/deploy cluster=<cluster-name>  [commit|pr|branch] [what-to-deploy]`
`/deploy cluster=<cluster-name> commit <commit-id>`
`/deploy cluster=<cluster-name>  pr [commit-id=]`
`/deploy cluster=<cluster-name> branch <branch name>`

**Comment by erichartline** [comment]
**Subcommand Examples**

`/deploy cluster=erickube commit=xyz`
`/deploy cluster=erickube pr`
`/deploy cluster=erickube pr commit=xyz`
`/deploy cluster=erickube branch=develop`

**Comment by erichartline** [comment]
For pull requests, the logic is as follows:

1) Commit ID provided
- need to use this ID as ref and as part of image tag
2) No commit ID provided
- need to fetch the head commit from the PR the comment came from

**Comment by erichartline** [comment]
**Updated commands:**

_Issues:_
`/deploy cluster=erickube commit=xyz`
`/deploy cluster=erickube branch=develop`

_PRs:_
`/deploy cluster=erickube`
`/deploy cluster=erickube commit=xyz`

No longer necessary to explicitly state `pr`, the script detects the comment origination and parses accordingly.
